### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by dhillondeep** [teamwaterloop/waterloop-website#55]
These are the error logs I am getting:

> templates@0.0.0 start /mnt/d/Others/Online Drives/Mega/Code/Waterloop/waterloop-website
> node ./bin/www

module.js:557
    throw err;
    ^

Error: Cannot find module '../secret/index.json'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Others/Online Drives/Mega/Code/Waterloop/waterloop-website/api/index.js:7:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! templates@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the templates@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-03T17_22_39_085Z-debug.log

**Comment by arora-aditya** [comment]
I just did: 
`git pull` and `npm start`

Have you tried: `npm install` before `npm start`
